./gettrace/src/BRIDGE/bridge_1x2.v
./gettrace/src/CONFREG/confreg.v
./gettrace/src/myCPU/SimpleLACoreWrapRAM.v
./gettrace/src/soc_lite_top.v
./gettrace/src/tb_top.v
./myCPU/alu.v
./myCPU/csr.v
./myCPU/mycpu_top.v
./myCPU/regfile.v
./myCPU/stage_ex.v
./myCPU/stage_id.v
./myCPU/stage_if.v
./myCPU/stage_mem.v
./myCPU/stage_wb.v
./myCPU/tools.v
./soc_verify/soc_hs_bram/rtl/BRIDGE/bridge_1x2.v
./soc_verify/soc_hs_bram/rtl/CONFREG/confreg.v
./soc_verify/soc_hs_bram/rtl/ram_wrap/sram_wrap.v
./soc_verify/soc_hs_bram/rtl/soc_lite_top.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/clk_pll/clk_pll_clk_wiz.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/clk_pll/clk_pll_sim_netlist.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/clk_pll/clk_pll_stub.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/clk_pll/clk_pll.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/data_ram/data_ram_sim_netlist.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/data_ram/data_ram_stub.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/data_ram/sim/data_ram.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/data_ram/simulation/blk_mem_gen_v8_4.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/inst_ram/inst_ram_sim_netlist.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/inst_ram/inst_ram_stub.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/inst_ram/sim/inst_ram.v
./soc_verify/soc_hs_bram/rtl/xilinx_ip/inst_ram/simulation/blk_mem_gen_v8_4.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.cache/ip/2023.2/a/2/a2cfc29e8561b4b8/inst_ram_sim_netlist.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.cache/ip/2023.2/a/2/a2cfc29e8561b4b8/inst_ram_stub.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.cache/ip/2023.2/b/1/b191b4caa0aae9b3/clk_pll_sim_netlist.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.cache/ip/2023.2/b/1/b191b4caa0aae9b3/clk_pll_stub.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.cache/ip/2023.2/c/9/c9714761c2f76722/data_ram_sim_netlist.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.cache/ip/2023.2/c/9/c9714761c2f76722/data_ram_stub.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/ip/clk_pll/clk_pll_stub.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/ip/data_ram/data_ram_stub.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/ip/inst_ram/inst_ram_stub.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/clk_pll/activehdl/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/clk_pll/modelsim/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/clk_pll/questa/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/clk_pll/riviera/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/clk_pll/vcs/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/clk_pll/xcelium/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/clk_pll/xsim/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/data_ram/activehdl/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/data_ram/modelsim/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/data_ram/questa/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/data_ram/riviera/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/data_ram/vcs/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/data_ram/xcelium/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/data_ram/xsim/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/inst_ram/activehdl/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/inst_ram/modelsim/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/inst_ram/questa/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/inst_ram/riviera/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/inst_ram/vcs/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/inst_ram/xcelium/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.ip_user_files/sim_scripts/inst_ram/xsim/glbl.v
./soc_verify/soc_hs_bram/run_vivado/project/loongson.sim/sim_1/behav/xsim/glbl.v
./soc_verify/soc_hs_bram/testbench/mycpu_tb.v
