./gettrace/src/BRIDGE/bridge_1x2.v
./gettrace/src/CONFREG/confreg.v
./gettrace/src/myCPU/SimpleLACoreWrapRAM.v
./gettrace/src/soc_lite_top.v
./gettrace/src/tb_top.v
./myCPU/alu.v
./myCPU/csr.v
./myCPU/macro.v
./myCPU/mycpu_top.v
./myCPU/regfile.v
./myCPU/sram_axi_bridge.v
./myCPU/stage_ex.v
./myCPU/stage_id.v
./myCPU/stage_if.v
./myCPU/stage_mem.v
./myCPU/stage_wb.v
./myCPU/tlb_searcher.sv
./myCPU/tlb.sv
./myCPU/tools.sv
./myCPU/tools.v
./soc_verify/soc_axi/rtl/axi_wrap/axi_wrap.v
./soc_verify/soc_axi/rtl/CONFREG/confreg.v
./soc_verify/soc_axi/rtl/ram_wrap/axi_wrap_ram.v
./soc_verify/soc_axi/rtl/soc_lite_top.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_sim_netlist.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_stub.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/hdl/axi_crossbar_v2_1_vl_rfs.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/hdl/axi_data_fifo_v2_1_vl_rfs.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/hdl/axi_infrastructure_v1_1_vl_rfs.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/hdl/axi_register_slice_v2_1_vl_rfs.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/hdl/fifo_generator_v13_2_rfs.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/hdl/generic_baseblocks_v2_1_vl_rfs.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/sim/axi_crossbar_1x2_stub.sv
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/sim/axi_crossbar_1x2.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/simulation/fifo_generator_vlog_beh.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/synth/axi_crossbar_1x2.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram_sim_netlist.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram_stub.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/sim/axi_ram.v
./soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/simulation/blk_mem_gen_v8_4.v
./soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll_clk_wiz.v
./soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll_sim_netlist.v
./soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll_stub.v
./soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll.v
./soc_verify/soc_axi/run_vivado/project/loongson.sim/sim_1/behav/xsim/glbl.v
./soc_verify/soc_axi/testbench/mycpu_tb.v
