./gettrace/src/BRIDGE/bridge_1x2.v
./gettrace/src/CONFREG/confreg.v
./gettrace/src/myCPU/SimpleLACoreWrapRAM.v
./gettrace/src/soc_lite_top.v
./gettrace/src/tb_top.v
./myCPU/alu.v
./myCPU/mycpu_top.v
./myCPU/regfile.v
./myCPU/stage_ex.v
./myCPU/stage_id.v
./myCPU/stage_mem.v
./myCPU/stage_wb.v
./myCPU/tools.v
./soc_verify/soc_bram/rtl/BRIDGE/bridge_1x2.v
./soc_verify/soc_bram/rtl/CONFREG/confreg.v
./soc_verify/soc_bram/rtl/soc_lite_top.v
./soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll_clk_wiz.v
./soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll_sim_netlist.v
./soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll_stub.v
./soc_verify/soc_bram/rtl/xilinx_ip/clk_pll/clk_pll.v
./soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram_sim_netlist.v
./soc_verify/soc_bram/rtl/xilinx_ip/data_ram/data_ram_stub.v
./soc_verify/soc_bram/rtl/xilinx_ip/data_ram/sim/data_ram.v
./soc_verify/soc_bram/rtl/xilinx_ip/data_ram/simulation/blk_mem_gen_v8_4.v
./soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram_sim_netlist.v
./soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/inst_ram_stub.v
./soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/sim/inst_ram.v
./soc_verify/soc_bram/rtl/xilinx_ip/inst_ram/simulation/blk_mem_gen_v8_4.v
./soc_verify/soc_bram/run_vivado/project/loongson.sim/sim_1/behav/xsim/glbl.v
./soc_verify/soc_bram/testbench/mycpu_tb.v
./soc_verify/soc_bram/testbench/sync_ram.v
./upload/myCPU/alu.v
./upload/myCPU/mycpu_top.v
./upload/myCPU/regfile.v
./upload/myCPU/stage_ex.v
./upload/myCPU/stage_id.v
./upload/myCPU/stage_mem.v
./upload/myCPU/stage_wb.v
./upload/myCPU/tools.v
