./gettrace/src/BRIDGE/bridge_1x2.v
./gettrace/src/CONFREG/confreg.v
./gettrace/src/myCPU/SimpleLACoreWrapRAM.v
./gettrace/src/soc_lite_top.v
./gettrace/src/tb_top.v
./myCPU/alu.v
./myCPU/mycpu_top.v
./myCPU/regfile.v
./myCPU/stage_ex.v
./myCPU/stage_id.v
./myCPU/stage_if.v
./myCPU/stage_mem.v
./myCPU/stage_wb.v
./myCPU/tools.v
./soc_verify/soc_bram/rtl/BRIDGE/bridge_1x2.v
./soc_verify/soc_bram/rtl/CONFREG/confreg.v
./soc_verify/soc_bram/rtl/soc_lite_top.v
./soc_verify/soc_bram/testbench/mycpu_tb.v
./soc_verify/soc_bram/testbench/sync_ram.v
